server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/susmitha61/fooddelivery-config
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 10
          username: susmitha61
          password: ${CONFIG_SERVER_PASSWORD:your-token-placeholder}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh